# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac9d313a05b0fc82761f336a94b8fbe6bf9442a4b88a20bd0cf25a9ac5b7d26bb674cbfb1a48d0a83059bc06345f1b794ed75ef0856fec2efa00053e8640f62

test:
  secret_key_base: 7bf09d5f7bfbca4e80f0fd97f2afdd49456b03c84f5380f9599d6903685c854b2d65951d57a02ec3a679d3f92b45f9092bbe9d0f42868567586b1422cb2b8ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
